server:
  port: 3000

path:
  publicImages: "public/images"
  query: "/tmp"

url:
  query: 'http://localhost:46921/api/ai/query'
  results: 'http://localhost:46921/api/ai/results'

log:
  appenders:
    console:
      type: console
      category: system
    file:
      type: dateFile
      filename: logs/system.log
      pattern: "-yyyy-MM-dd"
      alwaysIncludePattern: false
      category: system
  categories:
    default:
      appenders:
      - console
      - file
      level: info
    error:
      appenders:
      - console
      - file
      level: error
